Repository nxt-insurance/nxt_pipeline, pull requests merged in 2020-10, with the labels that each got.

#41 Update gemfile.lock
  Gemfile.lock
Labels: reviewed

#43 Refactor step class
  lib/nxt_pipeline/step.rb
Labels: please review

#42 Add step exection time
  CHANGELOG.md
  Gemfile.lock
  README.md
  lib/nxt_pipeline/step.rb
  lib/nxt_pipeline/version.rb
  spec/pipeline_spec.rb
Labels: please review, reviewed
